# Generated by Django 5.1.6 on 2025-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.AddField(
            model_name="users",
            name="force_password_change",
            field=models.BooleanField(default=False),
        ),
    ]
