# Generated by Django 5.1.6 on 2025-07-03 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lc_UserFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_id", models.CharField(max_length=255, unique=True)),
                ("file_type", models.CharField(default="unknown", max_length=50)),
                ("single_file_json", models.JSONField()),
                ("total_file_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lc_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lc_dt_userfiles",
            },
        ),
    ]
